# Generated by Django 5.2.4 on 2025-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addnotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
    ]
